version: "3"

networks:
  twitter-agg:
    external: false

services:
  twitteragg:
    image: pandects/twitter-agg
    container_name: twitter-agg
    build: ./twitter-agg
    environment:
        restart: always
    networks:
      - twitter-agg
    volumes:
      - ./twitter-agg:/usr/app