version: "3"

networks:
  twitter-agg:
    external: false

services:
  twitteragg:
    image: pandects/twitter-agg
    container_name: twitter-agg
    build: ./twitter-agg
    environment:
        restart: always
    networks:
      - twitter-agg
    volumes:
      - ./twitter-agg:/usr/app
    depends_on:
      - reverseproxy
    
  reverseproxy:
    image: pandects/twitter-agg-nginx
    container_name: twitter-agg-nginx
    build: ./nginx
    environment:
        restart: always
    networks:
      - twitter-agg
    ports:
      - "80:80"