version: "3"

networks:
  twitter-agg:
    external: false

services:
  twitteragg:
    image: 677374482341.dkr.ecr.eu-west-2.amazonaws.com/twitter-agg:latest
    container_name: twitter-agg
    env_file: twitter.env
    build: ./twitter-agg
    environment:
        restart: always
    networks:
      - twitter-agg
    #volumes:
    #  - ./twitter-agg:/usr/app
    ports:
      - 5000:5000